language: node_js
node_js:
  - "12"
services: mongodb
cache:
  directories:
    - "Backend/node_modules"
sudo: false
install:
  - cd ./Backend && npm install
script:
  - cd ./Backend && npm run test-unit
