language: node_js
node_js:
  - "12"
services: mongodb
before_script: cd /home/travis/build/Rainerino/CPEN-321/Backend
cache:
  directories:
    - "node_modules"
sudo: false
install:
  -  npm install
script:
  - npm run test-unit
